version: "3"
services:
  app:
    build: .
    image: registry.gitlab.com/invente/chase/apis/access-management-domain-apis:latest
    container_name: dev_access_mgnt
    restart: always
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
